services:
  db:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    expose:
      - 3306
      - 33060

  wordpress:
    image: wordpress:latest
    ports:
      - 8080:80
    restart: always
    volumes:
      - wp_data:/var/www/html
      - static_export:/var/www/html/export
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}

volumes:
  db_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .data/db
  wp_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .data/wp
  static_export:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: docs

